// User types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER = 'SET_USER';
export const SET_USER_IMAGE = 'SET_USER_IMAGE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// Snackbar types
export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS';
export const SNACKBAR_INFO = 'SNACKBAR_INFO';
export const SNACKBAR_WARNING = 'SNACKBAR_WARNING';
export const SNACKBAR_ERROR = 'SNACKBAR_ERROR';
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR';
// Search types
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
// Profile types
export const SET_BASIC_EDIT = 'SET_BASIC_EDIT';
export const SET_BIO_EDIT = 'SET_BIO_EDIT';
export const SET_EXPERIENCE_EDIT = 'SET_EXPERIENCE_EDIT';
export const SET_EDUCATION_EDIT = 'SET_EDUCATION_EDIT';
export const SET_ACHIEVEMENTS_EDIT = 'SET_ACHIEVEMENTS_EDIT';
export const SET_CLOSE_EDITS = 'SET_CLOSE_EDITS';
